keitaroUrl: test

spring:
  data:
    cassandra:
      keyspace-name: evaapp
      port: 9042
      local-datacenter: datacenter1
      schema-action: CREATE_IF_NOT_EXISTS

financialmodelingprep.apikey: test
onesignal:
  apiKey: test
  appId: test
