#---------------------------------------------------------------------
# Manifest File to create AWS EKS Cluster in Custom VPC
#
# eksctl create cluster -f eks-cluster.yaml
# eksctl delete cluster -f eks-cluster.yaml
#
# Copyleft (c) by Denis Astahov 2021
#---------------------------------------------------------------------
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name  : eva
  #region: us-west-2
  region: eu-west-1

#vpc:
#  id     : "vpc-02f918f0da766a6f0"
#  subnets:
#    public:
#      eu-west-1a: { id: subnet-083055488a87f39a4 }  # For Load Balancer
#      us-west-2b: { id: subnet-01940287d1c617f7c }  # For Load Balancer
#    private:
#      eu-west-1a: { id: subnet-0e5a0c43112216b89 }  # For Worker Nodes
#      us-west-2b: { id: subnet-04b4216e7f2adac45 }  # For Worker Nodes

