kind: ConfigMap
apiVersion: v1
metadata:
  name: {{override}}-configmap
data:
  application.yaml: |
    spring:
      data:
        cassandra:
          keyspace-name: {{override}}

    keitaroUrl:{{override}}
    financialmodelingprep.apikey: {{override}}
    onesignal:
      apiKey: {{override}}
      appId: {{override}}
