spring:
  data:
    cassandra:
      config: ''
      schema-action: CREATE_IF_NOT_EXISTS
      keyspace-name: evaapp
      request:
        consistency: local_quorum
      local-datacenter: datacenter1
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres
    baseline-on-migrate: true

keitaroUrl: test
financialmodelingprep.apikey: ''