
Запуск докер образа кассандры
docker run --rm -p 9042:9042 -d --name cassandra cassandra
docker run --rm --name habr-pg -p 5432:5432 -e POSTGRES_PASSWORD=postgres -d postgres

Публикация образа в облаке
aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/j6m7r3t6
docker build -t eva .
docker tag eva:latest public.ecr.aws/j6m7r3t6/eva:1.6.0-snapshot-arm64
docker push public.ecr.aws/j6m7r3t6/eva:1.6.0-snapshot-arm64